issuer: http://localhost:{{ .Env.DEX_PORT }}/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: {{ .Env.OAUTH2_PROXY_CLIENT_ID }}
    secret: {{ .Env.OAUTH2_PROXY_CLIENT_SECRET }}
    redirectURIs:
      - http://localhost:{{ .Env.OAUTH2_PROXY_PORT }}/oauth2/callback
    name: Full Stack CEN Template (dev)

oauth2:
  skipApprovalScreen: true

enablePasswordDB: true

staticPasswords:
  - email: admin@example.com
    username: admin
    userID: 11111111-1111-1111-1111-111111111111
    hash: "$2a$10$V0rr.FG49/FTYTfckSbEdeInTpmUAyh0DHWl9lyj5S/AVnNJtz2Dy"
