// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  ItemsCreateItemData,
  ItemsCreateItemErrors,
  ItemsCreateItemResponses,
  ItemsDeleteItemData,
  ItemsDeleteItemErrors,
  ItemsDeleteItemResponses,
  ItemsReadItemData,
  ItemsReadItemErrors,
  ItemsReadItemResponses,
  ItemsReadItemsData,
  ItemsReadItemsErrors,
  ItemsReadItemsResponses,
  ItemsUpdateItemData,
  ItemsUpdateItemErrors,
  ItemsUpdateItemResponses,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenErrors,
  LoginLoginAccessTokenResponses,
  LoginTestTokenData,
  LoginTestTokenResponses,
  TicketsDeleteTicketData,
  TicketsDeleteTicketErrors,
  TicketsDeleteTicketResponses,
  TicketsDownloadTicketPdfData,
  TicketsDownloadTicketPdfErrors,
  TicketsDownloadTicketPdfResponses,
  TicketsGetDashboardStatsData,
  TicketsGetDashboardStatsResponses,
  TicketsGetRecentScansData,
  TicketsGetRecentScansErrors,
  TicketsGetRecentScansResponses,
  TicketsReadTicketData,
  TicketsReadTicketErrors,
  TicketsReadTicketResponses,
  TicketsReadTicketsByHostData,
  TicketsReadTicketsByHostErrors,
  TicketsReadTicketsByHostResponses,
  TicketsReadTicketScanEventsData,
  TicketsReadTicketScanEventsErrors,
  TicketsReadTicketScanEventsResponses,
  TicketsReadTicketsData,
  TicketsReadTicketsErrors,
  TicketsReadTicketsResponses,
  TicketsUpdateTicketData,
  TicketsUpdateTicketErrors,
  TicketsUpdateTicketResponses,
  TicketsUploadCsvAndGenerateTicketsData,
  TicketsUploadCsvAndGenerateTicketsErrors,
  TicketsUploadCsvAndGenerateTicketsResponses,
  TicketsValidateTicketData,
  TicketsValidateTicketErrors,
  TicketsValidateTicketResponses,
  UsersCreateUserData,
  UsersCreateUserErrors,
  UsersCreateUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserMeData,
  UsersDeleteUserMeResponses,
  UsersDeleteUserResponses,
  UsersReadUserByIdData,
  UsersReadUserByIdErrors,
  UsersReadUserByIdResponses,
  UsersReadUserMeData,
  UsersReadUserMeResponses,
  UsersReadUsersData,
  UsersReadUsersErrors,
  UsersReadUsersResponses,
  UsersRegisterUserData,
  UsersRegisterUserErrors,
  UsersRegisterUserResponses,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeErrors,
  UsersUpdatePasswordMeResponses,
  UsersUpdateUserData,
  UsersUpdateUserErrors,
  UsersUpdateUserMeData,
  UsersUpdateUserMeErrors,
  UsersUpdateUserMeResponses,
  UsersUpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Login {
  /**
   * Login Access Token
   *
   * OAuth2 compatible token login, get an access token for future requests
   */
  public static loginLoginAccessToken<ThrowOnError extends boolean = false>(
    options: Options<LoginLoginAccessTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LoginLoginAccessTokenResponses,
      LoginLoginAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      responseType: "json",
      url: "/api/v1/login/access-token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    });
  }

  /**
   * Test Token
   *
   * Test access token
   */
  public static loginTestToken<ThrowOnError extends boolean = false>(
    options?: Options<LoginTestTokenData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      LoginTestTokenResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/login/test-token",
      ...options,
    });
  }
}

export class Users {
  /**
   * Read Users
   *
   * Retrieve users.
   */
  public static usersReadUsers<ThrowOnError extends boolean = false>(
    options?: Options<UsersReadUsersData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UsersReadUsersResponses,
      UsersReadUsersErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
    });
  }

  /**
   * Create User
   *
   * Create new user.
   */
  public static usersCreateUser<ThrowOnError extends boolean = false>(
    options: Options<UsersCreateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      UsersCreateUserResponses,
      UsersCreateUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete User Me
   *
   * Delete own user.
   */
  public static usersDeleteUserMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersDeleteUserMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).delete<
      UsersDeleteUserMeResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    });
  }

  /**
   * Read User Me
   *
   * Get current user.
   */
  public static usersReadUserMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersReadUserMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UsersReadUserMeResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    });
  }

  /**
   * Update User Me
   *
   * Update own user.
   */
  public static usersUpdateUserMe<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateUserMeData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UsersUpdateUserMeResponses,
      UsersUpdateUserMeErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Update Password Me
   *
   * Update own password.
   */
  public static usersUpdatePasswordMe<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdatePasswordMeData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UsersUpdatePasswordMeResponses,
      UsersUpdatePasswordMeErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me/password",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Register User
   *
   * Create new user without the need to be logged in.
   */
  public static usersRegisterUser<ThrowOnError extends boolean = false>(
    options: Options<UsersRegisterUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      UsersRegisterUserResponses,
      UsersRegisterUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/users/signup",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete User
   *
   * Delete a user.
   */
  public static usersDeleteUser<ThrowOnError extends boolean = false>(
    options: Options<UsersDeleteUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      UsersDeleteUserResponses,
      UsersDeleteUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    });
  }

  /**
   * Read User By Id
   *
   * Get a specific user by id.
   */
  public static usersReadUserById<ThrowOnError extends boolean = false>(
    options: Options<UsersReadUserByIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      UsersReadUserByIdResponses,
      UsersReadUserByIdErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    });
  }

  /**
   * Update User
   *
   * Update a user.
   */
  public static usersUpdateUser<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UsersUpdateUserResponses,
      UsersUpdateUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Items {
  /**
   * Read Items
   *
   * Retrieve items.
   */
  public static itemsReadItems<ThrowOnError extends boolean = false>(
    options?: Options<ItemsReadItemsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ItemsReadItemsResponses,
      ItemsReadItemsErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
    });
  }

  /**
   * Create Item
   *
   * Create new item.
   */
  public static itemsCreateItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsCreateItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      ItemsCreateItemResponses,
      ItemsCreateItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Item
   *
   * Delete an item.
   */
  public static itemsDeleteItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsDeleteItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      ItemsDeleteItemResponses,
      ItemsDeleteItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Read Item
   *
   * Get item by ID.
   */
  public static itemsReadItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsReadItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      ItemsReadItemResponses,
      ItemsReadItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Update Item
   *
   * Update an item.
   */
  public static itemsUpdateItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsUpdateItemData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      ItemsUpdateItemResponses,
      ItemsUpdateItemErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Tickets {
  /**
   * Upload Csv And Generate Tickets
   *
   * Upload CSV file and generate tickets for all guests.
   *
   * Expected CSV format (Airtable export):
   * - Semicolon delimiter
   * - UTF-8 with BOM encoding
   * - Columns: Vorname, Nachname, E-Mail, Rolle, Age Guest, E-mail Host Gast
   *
   * Returns:
   * Dictionary with success count, error count, and details
   */
  public static ticketsUploadCsvAndGenerateTickets<
    ThrowOnError extends boolean = false,
  >(options: Options<TicketsUploadCsvAndGenerateTicketsData, ThrowOnError>) {
    return (options.client ?? client).post<
      TicketsUploadCsvAndGenerateTicketsResponses,
      TicketsUploadCsvAndGenerateTicketsErrors,
      ThrowOnError
    >({
      ...formDataBodySerializer,
      responseType: "json",
      url: "/api/v1/tickets/upload-csv",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    });
  }

  /**
   * Read Tickets
   *
   * Get all tickets with pagination.
   */
  public static ticketsReadTickets<ThrowOnError extends boolean = false>(
    options?: Options<TicketsReadTicketsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TicketsReadTicketsResponses,
      TicketsReadTicketsErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/",
      ...options,
    });
  }

  /**
   * Read Tickets By Host
   *
   * Get all tickets for a specific host (IBMer).
   */
  public static ticketsReadTicketsByHost<ThrowOnError extends boolean = false>(
    options: Options<TicketsReadTicketsByHostData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      TicketsReadTicketsByHostResponses,
      TicketsReadTicketsByHostErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/by-host/{host_email}",
      ...options,
    });
  }

  /**
   * Get Dashboard Stats
   *
   * Get real-time dashboard statistics for ticket monitoring.
   *
   * Returns:
   * Dictionary with total tickets, scanned tickets, remaining tickets, and scan rate
   */
  public static ticketsGetDashboardStats<ThrowOnError extends boolean = false>(
    options?: Options<TicketsGetDashboardStatsData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TicketsGetDashboardStatsResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/dashboard",
      ...options,
    });
  }

  /**
   * Get Recent Scans
   *
   * Get recent scan events for monitoring dashboard.
   *
   * Returns the last N scan events with ticket details, ordered by timestamp descending.
   *
   * Args:
   * limit: Maximum number of scan events to return (default: 50)
   *
   * Returns:
   * ScanEventsPublic with recent scan events
   */
  public static ticketsGetRecentScans<ThrowOnError extends boolean = false>(
    options?: Options<TicketsGetRecentScansData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      TicketsGetRecentScansResponses,
      TicketsGetRecentScansErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/recent-scans",
      ...options,
    });
  }

  /**
   * Delete Ticket
   *
   * Delete a ticket by ID.
   */
  public static ticketsDeleteTicket<ThrowOnError extends boolean = false>(
    options: Options<TicketsDeleteTicketData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      TicketsDeleteTicketResponses,
      TicketsDeleteTicketErrors,
      ThrowOnError
    >({ url: "/api/v1/tickets/{ticket_id}", ...options });
  }

  /**
   * Read Ticket
   *
   * Get a specific ticket by ID.
   */
  public static ticketsReadTicket<ThrowOnError extends boolean = false>(
    options: Options<TicketsReadTicketData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      TicketsReadTicketResponses,
      TicketsReadTicketErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/{ticket_id}",
      ...options,
    });
  }

  /**
   * Update Ticket
   *
   * Update a ticket.
   */
  public static ticketsUpdateTicket<ThrowOnError extends boolean = false>(
    options: Options<TicketsUpdateTicketData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      TicketsUpdateTicketResponses,
      TicketsUpdateTicketErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/{ticket_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Download Ticket Pdf
   *
   * Download ticket as PDF.
   */
  public static ticketsDownloadTicketPdf<ThrowOnError extends boolean = false>(
    options: Options<TicketsDownloadTicketPdfData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      TicketsDownloadTicketPdfResponses,
      TicketsDownloadTicketPdfErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/{ticket_id}/pdf",
      ...options,
    });
  }

  /**
   * Validate Ticket
   *
   * Validate a ticket for entry (real-time duplicate prevention).
   *
   * Uses row-level locking (SELECT ... FOR UPDATE) to prevent race conditions
   * when multiple scanners attempt to validate the same ticket simultaneously.
   *
   * Returns:
   * Dictionary with validation result and ticket status
   */
  public static ticketsValidateTicket<ThrowOnError extends boolean = false>(
    options: Options<TicketsValidateTicketData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      TicketsValidateTicketResponses,
      TicketsValidateTicketErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/{ticket_id}/validate",
      ...options,
    });
  }

  /**
   * Read Ticket Scan Events
   *
   * Get all scan events for a specific ticket (audit trail).
   */
  public static ticketsReadTicketScanEvents<
    ThrowOnError extends boolean = false,
  >(options: Options<TicketsReadTicketScanEventsData, ThrowOnError>) {
    return (options.client ?? client).get<
      TicketsReadTicketScanEventsResponses,
      TicketsReadTicketScanEventsErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/tickets/{ticket_id}/scan-events",
      ...options,
    });
  }
}
