// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  ReadItemData,
  ReadItemErrors,
  ReadItemResponses,
  ReadItemsData,
  ReadItemsErrors,
  ReadItemsResponses,
  ReadUserMeData,
  ReadUserMeResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Users {
  /**
   * Read User Me
   *
   * Get current user.
   */
  public static readUserMe<ThrowOnError extends boolean = false>(
    options?: Options<ReadUserMeData, ThrowOnError>,
  ): RequestResult<ReadUserMeResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<ReadUserMeResponses, unknown, ThrowOnError>({
      responseType: "json",
      url: "/api/v1/users/me",
      ...options,
    });
  }
}

export class Items {
  /**
   * Read Items
   *
   * Retrieve items.
   */
  public static readItems<ThrowOnError extends boolean = false>(
    options?: Options<ReadItemsData, ThrowOnError>,
  ): RequestResult<ReadItemsResponses, ReadItemsErrors, ThrowOnError> {
    return (options?.client ?? client).get<ReadItemsResponses, ReadItemsErrors, ThrowOnError>({
      responseType: "json",
      url: "/api/v1/items/",
      ...options,
    });
  }

  /**
   * Create Item
   *
   * Create new item.
   */
  public static createItem<ThrowOnError extends boolean = false>(
    options: Options<CreateItemData, ThrowOnError>,
  ): RequestResult<CreateItemResponses, CreateItemErrors, ThrowOnError> {
    return (options.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
      responseType: "json",
      url: "/api/v1/items/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Item
   *
   * Delete an item.
   */
  public static deleteItem<ThrowOnError extends boolean = false>(
    options: Options<DeleteItemData, ThrowOnError>,
  ): RequestResult<DeleteItemResponses, DeleteItemErrors, ThrowOnError> {
    return (options.client ?? client).delete<DeleteItemResponses, DeleteItemErrors, ThrowOnError>({
      responseType: "json",
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Read Item
   *
   * Get item by ID.
   */
  public static readItem<ThrowOnError extends boolean = false>(
    options: Options<ReadItemData, ThrowOnError>,
  ): RequestResult<ReadItemResponses, ReadItemErrors, ThrowOnError> {
    return (options.client ?? client).get<ReadItemResponses, ReadItemErrors, ThrowOnError>({
      responseType: "json",
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Update Item
   *
   * Update an item.
   */
  public static updateItem<ThrowOnError extends boolean = false>(
    options: Options<UpdateItemData, ThrowOnError>,
  ): RequestResult<UpdateItemResponses, UpdateItemErrors, ThrowOnError> {
    return (options.client ?? client).put<UpdateItemResponses, UpdateItemErrors, ThrowOnError>({
      responseType: "json",
      url: "/api/v1/items/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
