// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserMeData,
  DeleteUserMeResponses,
  DeleteUserResponses,
  LoginAccessTokenData,
  LoginAccessTokenErrors,
  LoginAccessTokenResponses,
  ReadItemData,
  ReadItemErrors,
  ReadItemResponses,
  ReadItemsData,
  ReadItemsErrors,
  ReadItemsResponses,
  ReadUserByIdData,
  ReadUserByIdErrors,
  ReadUserByIdResponses,
  ReadUserMeData,
  ReadUserMeResponses,
  ReadUsersData,
  ReadUsersErrors,
  ReadUsersResponses,
  RegisterUserData,
  RegisterUserErrors,
  RegisterUserResponses,
  TestTokenData,
  TestTokenResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
  UpdatePasswordMeData,
  UpdatePasswordMeErrors,
  UpdatePasswordMeResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserMeData,
  UpdateUserMeErrors,
  UpdateUserMeResponses,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Login {
  /**
   * Login Access Token
   *
   * OAuth2 compatible token login, get an access token for future requests
   */
  public static loginAccessToken<ThrowOnError extends boolean = false>(
    options: Options<LoginAccessTokenData, ThrowOnError>,
  ): RequestResult<LoginAccessTokenResponses, LoginAccessTokenErrors, ThrowOnError> {
    return (options.client ?? client).post<
      LoginAccessTokenResponses,
      LoginAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      responseType: "json",
      url: "/api/v1/login/access-token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    });
  }

  /**
   * Test Token
   *
   * Test access token
   */
  public static testToken<ThrowOnError extends boolean = false>(
    options?: Options<TestTokenData, ThrowOnError>,
  ): RequestResult<TestTokenResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).post<TestTokenResponses, unknown, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/login/test-token",
      ...options,
    });
  }
}

export class Users {
  /**
   * Read Users
   *
   * Retrieve users.
   */
  public static readUsers<ThrowOnError extends boolean = false>(
    options?: Options<ReadUsersData, ThrowOnError>,
  ): RequestResult<ReadUsersResponses, ReadUsersErrors, ThrowOnError> {
    return (options?.client ?? client).get<ReadUsersResponses, ReadUsersErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
    });
  }

  /**
   * Create User
   *
   * Create new user.
   */
  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<CreateUserData, ThrowOnError>,
  ): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> {
    return (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete User Me
   *
   * Delete own user.
   */
  public static deleteUserMe<ThrowOnError extends boolean = false>(
    options?: Options<DeleteUserMeData, ThrowOnError>,
  ): RequestResult<DeleteUserMeResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).delete<DeleteUserMeResponses, unknown, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    });
  }

  /**
   * Read User Me
   *
   * Get current user.
   */
  public static readUserMe<ThrowOnError extends boolean = false>(
    options?: Options<ReadUserMeData, ThrowOnError>,
  ): RequestResult<ReadUserMeResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<ReadUserMeResponses, unknown, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    });
  }

  /**
   * Update User Me
   *
   * Update own user.
   */
  public static updateUserMe<ThrowOnError extends boolean = false>(
    options: Options<UpdateUserMeData, ThrowOnError>,
  ): RequestResult<UpdateUserMeResponses, UpdateUserMeErrors, ThrowOnError> {
    return (options.client ?? client).patch<
      UpdateUserMeResponses,
      UpdateUserMeErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Update Password Me
   *
   * Update own password.
   */
  public static updatePasswordMe<ThrowOnError extends boolean = false>(
    options: Options<UpdatePasswordMeData, ThrowOnError>,
  ): RequestResult<UpdatePasswordMeResponses, UpdatePasswordMeErrors, ThrowOnError> {
    return (options.client ?? client).patch<
      UpdatePasswordMeResponses,
      UpdatePasswordMeErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me/password",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Register User
   *
   * Create new user without the need to be logged in.
   */
  public static registerUser<ThrowOnError extends boolean = false>(
    options: Options<RegisterUserData, ThrowOnError>,
  ): RequestResult<RegisterUserResponses, RegisterUserErrors, ThrowOnError> {
    return (options.client ?? client).post<RegisterUserResponses, RegisterUserErrors, ThrowOnError>(
      {
        responseType: "json",
        url: "/api/v1/users/signup",
        ...options,
        headers: {
          "Content-Type": "application/json",
          ...options.headers,
        },
      },
    );
  }

  /**
   * Delete User
   *
   * Delete a user.
   */
  public static deleteUser<ThrowOnError extends boolean = false>(
    options: Options<DeleteUserData, ThrowOnError>,
  ): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> {
    return (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    });
  }

  /**
   * Read User By Id
   *
   * Get a specific user by id.
   */
  public static readUserById<ThrowOnError extends boolean = false>(
    options: Options<ReadUserByIdData, ThrowOnError>,
  ): RequestResult<ReadUserByIdResponses, ReadUserByIdErrors, ThrowOnError> {
    return (options.client ?? client).get<ReadUserByIdResponses, ReadUserByIdErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    });
  }

  /**
   * Update User
   *
   * Update a user.
   */
  public static updateUser<ThrowOnError extends boolean = false>(
    options: Options<UpdateUserData, ThrowOnError>,
  ): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> {
    return (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Items {
  /**
   * Read Items
   *
   * Retrieve items.
   */
  public static readItems<ThrowOnError extends boolean = false>(
    options?: Options<ReadItemsData, ThrowOnError>,
  ): RequestResult<ReadItemsResponses, ReadItemsErrors, ThrowOnError> {
    return (options?.client ?? client).get<ReadItemsResponses, ReadItemsErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
    });
  }

  /**
   * Create Item
   *
   * Create new item.
   */
  public static createItem<ThrowOnError extends boolean = false>(
    options: Options<CreateItemData, ThrowOnError>,
  ): RequestResult<CreateItemResponses, CreateItemErrors, ThrowOnError> {
    return (options.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete Item
   *
   * Delete an item.
   */
  public static deleteItem<ThrowOnError extends boolean = false>(
    options: Options<DeleteItemData, ThrowOnError>,
  ): RequestResult<DeleteItemResponses, DeleteItemErrors, ThrowOnError> {
    return (options.client ?? client).delete<DeleteItemResponses, DeleteItemErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Read Item
   *
   * Get item by ID.
   */
  public static readItem<ThrowOnError extends boolean = false>(
    options: Options<ReadItemData, ThrowOnError>,
  ): RequestResult<ReadItemResponses, ReadItemErrors, ThrowOnError> {
    return (options.client ?? client).get<ReadItemResponses, ReadItemErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    });
  }

  /**
   * Update Item
   *
   * Update an item.
   */
  public static updateItem<ThrowOnError extends boolean = false>(
    options: Options<UpdateItemData, ThrowOnError>,
  ): RequestResult<UpdateItemResponses, UpdateItemErrors, ThrowOnError> {
    return (options.client ?? client).put<UpdateItemResponses, UpdateItemErrors, ThrowOnError>({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
