// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Owner Id
   */
  owner_id: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
  /**
   * Data
   */
  data: Array<ItemPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * Message
 */
export type Message = {
  /**
   * Message
   */
  message: string;
};

/**
 * User
 */
export type User = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ReadUserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type ReadUserMeResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type ReadItemsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items/";
};

export type ReadItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemsError = ReadItemsErrors[keyof ReadItemsErrors];

export type ReadItemsResponses = {
  /**
   * Successful Response
   */
  200: ItemsPublic;
};

export type ReadItemsResponse = ReadItemsResponses[keyof ReadItemsResponses];

export type CreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type ReadItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type UpdateItemData = {
  body: ItemUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type UpdateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];
