// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * Body_tickets-upload_csv_and_generate_tickets
 */
export type BodyTicketsUploadCsvAndGenerateTickets = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * EmailStatus
 */
export type EmailStatus =
  | "pending"
  | "processing"
  | "sent"
  | "failed"
  | "bounced";

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Owner Id
   */
  owner_id: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
  /**
   * Data
   */
  data: Array<ItemPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * Message
 */
export type Message = {
  /**
   * Message
   */
  message: string;
};

/**
 * ScanEventPublic
 */
export type ScanEventPublic = {
  /**
   * Id
   */
  id: string;
  /**
   * Ticket Id
   */
  ticket_id: string;
  /**
   * Timestamp
   */
  timestamp: string;
  /**
   * Scanner Device Id
   */
  scanner_device_id: string;
  /**
   * Scanner User Id
   */
  scanner_user_id: string;
  scan_result: ScanResult;
  /**
   * Error Message
   */
  error_message: string | null;
  /**
   * Network Latency Ms
   */
  network_latency_ms: number | null;
};

/**
 * ScanEventsPublic
 */
export type ScanEventsPublic = {
  /**
   * Data
   */
  data: Array<ScanEventPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * ScanResult
 */
export type ScanResult =
  | "granted"
  | "already_scanned"
  | "invalid"
  | "network_error";

/**
 * TicketPublic
 */
export type TicketPublic = {
  /**
   * First Name
   */
  first_name: string;
  /**
   * Last Name
   */
  last_name: string;
  /**
   * Guest Email
   */
  guest_email: string;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Host Email
   */
  host_email: string;
  /**
   * Guest Age
   */
  guest_age?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Qr Code Data
   */
  qr_code_data: string;
  /**
   * Is Scanned
   */
  is_scanned: boolean;
  /**
   * Scanned At
   */
  scanned_at: string | null;
  /**
   * Scanner Device Id
   */
  scanner_device_id: string | null;
  /**
   * Scanner User Id
   */
  scanner_user_id: string | null;
  /**
   * Email Sent
   */
  email_sent: boolean;
  /**
   * Email Sent At
   */
  email_sent_at: string | null;
  email_delivery_status: EmailStatus;
  /**
   * Email Retry Count
   */
  email_retry_count: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * TicketUpdate
 */
export type TicketUpdate = {
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Guest Email
   */
  guest_email?: string | null;
  /**
   * Role
   */
  role?: string | null;
  /**
   * Host Email
   */
  host_email?: string | null;
  /**
   * Guest Age
   */
  guest_age?: string | null;
};

/**
 * TicketsPublic
 */
export type TicketsPublic = {
  /**
   * Data
   */
  data: Array<TicketPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
  /**
   * Current Password
   */
  current_password: string;
  /**
   * New Password
   */
  new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Id
   */
  id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Access Password
   */
  access_password?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Password
   */
  password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
  /**
   * Data
   */
  data: Array<UserPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type LoginLoginAccessTokenData = {
  body: BodyLoginLoginAccessToken;
  path?: never;
  query?: never;
  url: "/api/v1/login/access-token";
};

export type LoginLoginAccessTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginLoginAccessTokenError =
  LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginLoginAccessTokenResponse =
  LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/login/test-token";
};

export type LoginTestTokenResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type LoginTestTokenResponse =
  LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type UsersReadUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/users/";
};

export type UsersReadUsersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersReadUsersError =
  UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
  /**
   * Successful Response
   */
  200: UsersPublic;
};

export type UsersReadUsersResponse =
  UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/users/";
};

export type UsersCreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersCreateUserError =
  UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UsersCreateUserResponse =
  UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersDeleteUserMeResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type UsersDeleteUserMeResponse =
  UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersReadUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UsersReadUserMeResponse =
  UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
  body: UserUpdateMe;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UsersUpdateUserMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUpdateUserMeError =
  UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UsersUpdateUserMeResponse =
  UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
  body: UpdatePassword;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/password";
};

export type UsersUpdatePasswordMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUpdatePasswordMeError =
  UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type UsersUpdatePasswordMeResponse =
  UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
  body: UserRegister;
  path?: never;
  query?: never;
  url: "/api/v1/users/signup";
};

export type UsersRegisterUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersRegisterUserError =
  UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UsersRegisterUserResponse =
  UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/users/{user_id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/users/{user_id}";
};

export type UsersReadUserByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersReadUserByIdError =
  UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UsersReadUserByIdResponse =
  UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
  body: UserUpdate;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/users/{user_id}";
};

export type UsersUpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUpdateUserError =
  UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UsersUpdateUserResponse =
  UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type ItemsReadItemsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items/";
};

export type ItemsReadItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemsReadItemsError =
  ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
  /**
   * Successful Response
   */
  200: ItemsPublic;
};

export type ItemsReadItemsResponse =
  ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type ItemsCreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemsCreateItemError =
  ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type ItemsCreateItemResponse =
  ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type ItemsDeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemsDeleteItemError =
  ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type ItemsDeleteItemResponse =
  ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type ItemsReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type ItemsReadItemResponse =
  ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
  body: ItemUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type ItemsUpdateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ItemsUpdateItemError =
  ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type ItemsUpdateItemResponse =
  ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type TicketsUploadCsvAndGenerateTicketsData = {
  body: BodyTicketsUploadCsvAndGenerateTickets;
  path?: never;
  query?: never;
  url: "/api/v1/tickets/upload-csv";
};

export type TicketsUploadCsvAndGenerateTicketsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsUploadCsvAndGenerateTicketsError =
  TicketsUploadCsvAndGenerateTicketsErrors[keyof TicketsUploadCsvAndGenerateTicketsErrors];

export type TicketsUploadCsvAndGenerateTicketsResponses = {
  /**
   * Response Tickets-Upload Csv And Generate Tickets
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type TicketsUploadCsvAndGenerateTicketsResponse =
  TicketsUploadCsvAndGenerateTicketsResponses[keyof TicketsUploadCsvAndGenerateTicketsResponses];

export type TicketsReadTicketsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/tickets/";
};

export type TicketsReadTicketsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsReadTicketsError =
  TicketsReadTicketsErrors[keyof TicketsReadTicketsErrors];

export type TicketsReadTicketsResponses = {
  /**
   * Successful Response
   */
  200: TicketsPublic;
};

export type TicketsReadTicketsResponse =
  TicketsReadTicketsResponses[keyof TicketsReadTicketsResponses];

export type TicketsReadTicketsByHostData = {
  body?: never;
  path: {
    /**
     * Host Email
     */
    host_email: string;
  };
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/tickets/by-host/{host_email}";
};

export type TicketsReadTicketsByHostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsReadTicketsByHostError =
  TicketsReadTicketsByHostErrors[keyof TicketsReadTicketsByHostErrors];

export type TicketsReadTicketsByHostResponses = {
  /**
   * Successful Response
   */
  200: TicketsPublic;
};

export type TicketsReadTicketsByHostResponse =
  TicketsReadTicketsByHostResponses[keyof TicketsReadTicketsByHostResponses];

export type TicketsGetDashboardStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/tickets/dashboard";
};

export type TicketsGetDashboardStatsResponses = {
  /**
   * Response Tickets-Get Dashboard Stats
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type TicketsGetDashboardStatsResponse =
  TicketsGetDashboardStatsResponses[keyof TicketsGetDashboardStatsResponses];

export type TicketsGetRecentScansData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/tickets/recent-scans";
};

export type TicketsGetRecentScansErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsGetRecentScansError =
  TicketsGetRecentScansErrors[keyof TicketsGetRecentScansErrors];

export type TicketsGetRecentScansResponses = {
  /**
   * Successful Response
   */
  200: ScanEventsPublic;
};

export type TicketsGetRecentScansResponse =
  TicketsGetRecentScansResponses[keyof TicketsGetRecentScansResponses];

export type TicketsDeleteTicketData = {
  body?: never;
  path: {
    /**
     * Ticket Id
     */
    ticket_id: string;
  };
  query?: never;
  url: "/api/v1/tickets/{ticket_id}";
};

export type TicketsDeleteTicketErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsDeleteTicketError =
  TicketsDeleteTicketErrors[keyof TicketsDeleteTicketErrors];

export type TicketsDeleteTicketResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type TicketsDeleteTicketResponse =
  TicketsDeleteTicketResponses[keyof TicketsDeleteTicketResponses];

export type TicketsReadTicketData = {
  body?: never;
  path: {
    /**
     * Ticket Id
     */
    ticket_id: string;
  };
  query?: never;
  url: "/api/v1/tickets/{ticket_id}";
};

export type TicketsReadTicketErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsReadTicketError =
  TicketsReadTicketErrors[keyof TicketsReadTicketErrors];

export type TicketsReadTicketResponses = {
  /**
   * Successful Response
   */
  200: TicketPublic;
};

export type TicketsReadTicketResponse =
  TicketsReadTicketResponses[keyof TicketsReadTicketResponses];

export type TicketsUpdateTicketData = {
  body: TicketUpdate;
  path: {
    /**
     * Ticket Id
     */
    ticket_id: string;
  };
  query?: never;
  url: "/api/v1/tickets/{ticket_id}";
};

export type TicketsUpdateTicketErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsUpdateTicketError =
  TicketsUpdateTicketErrors[keyof TicketsUpdateTicketErrors];

export type TicketsUpdateTicketResponses = {
  /**
   * Successful Response
   */
  200: TicketPublic;
};

export type TicketsUpdateTicketResponse =
  TicketsUpdateTicketResponses[keyof TicketsUpdateTicketResponses];

export type TicketsDownloadTicketPdfData = {
  body?: never;
  path: {
    /**
     * Ticket Id
     */
    ticket_id: string;
  };
  query?: never;
  url: "/api/v1/tickets/{ticket_id}/pdf";
};

export type TicketsDownloadTicketPdfErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsDownloadTicketPdfError =
  TicketsDownloadTicketPdfErrors[keyof TicketsDownloadTicketPdfErrors];

export type TicketsDownloadTicketPdfResponses = {
  /**
   * Response Tickets-Download Ticket Pdf
   *
   * Successful Response
   */
  200: unknown;
};

export type TicketsValidateTicketData = {
  body?: never;
  path: {
    /**
     * Ticket Id
     */
    ticket_id: string;
  };
  query?: {
    /**
     * Scanner Device Id
     */
    scanner_device_id?: string;
    /**
     * Scanner User Id
     */
    scanner_user_id?: string;
  };
  url: "/api/v1/tickets/{ticket_id}/validate";
};

export type TicketsValidateTicketErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsValidateTicketError =
  TicketsValidateTicketErrors[keyof TicketsValidateTicketErrors];

export type TicketsValidateTicketResponses = {
  /**
   * Response Tickets-Validate Ticket
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type TicketsValidateTicketResponse =
  TicketsValidateTicketResponses[keyof TicketsValidateTicketResponses];

export type TicketsReadTicketScanEventsData = {
  body?: never;
  path: {
    /**
     * Ticket Id
     */
    ticket_id: string;
  };
  query?: never;
  url: "/api/v1/tickets/{ticket_id}/scan-events";
};

export type TicketsReadTicketScanEventsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TicketsReadTicketScanEventsError =
  TicketsReadTicketScanEventsErrors[keyof TicketsReadTicketScanEventsErrors];

export type TicketsReadTicketScanEventsResponses = {
  /**
   * Successful Response
   */
  200: ScanEventsPublic;
};

export type TicketsReadTicketScanEventsResponse =
  TicketsReadTicketScanEventsResponses[keyof TicketsReadTicketScanEventsResponses];
