"""increase qr_code_data field length to 10000

Revision ID: 8ed5e9710555
Revises: ca1e4cae0f8f
Create Date: 2026-05-04 23:15:29.956991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8ed5e9710555'
down_revision = 'ca1e4cae0f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'qr_code_data',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'qr_code_data',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
