"""Increase qr_code_data field length to 20000 characters

Revision ID: bd117dfc6cd0
Revises: 8ed5e9710555
Create Date: 2026-05-04 23:21:17.759124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bd117dfc6cd0'
down_revision = '8ed5e9710555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'qr_code_data',
               existing_type=sa.VARCHAR(length=10000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'qr_code_data',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###
