"""Add ticket scan event and email queue tables

Revision ID: ca1e4cae0f8f
Revises: 1a31ce608336
Create Date: 2026-05-04 22:09:53.404981

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca1e4cae0f8f'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('guest_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('host_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('guest_age', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qr_code_data', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('scanner_device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('scanner_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_delivery_status', sa.Enum('pending', 'processing', 'sent', 'failed', 'bounced', name='emailstatus'), nullable=False),
    sa.Column('email_retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_created_at'), 'ticket', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_email_delivery_status'), 'ticket', ['email_delivery_status'], unique=False)
    op.create_index(op.f('ix_ticket_guest_email'), 'ticket', ['guest_email'], unique=False)
    op.create_index(op.f('ix_ticket_host_email'), 'ticket', ['host_email'], unique=False)
    op.create_index(op.f('ix_ticket_is_scanned'), 'ticket', ['is_scanned'], unique=False)
    op.create_table('emailqueue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('html_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_attachment_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'sent', 'failed', 'bounced', name='emailstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailqueue_next_retry_at'), 'emailqueue', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_emailqueue_status'), 'emailqueue', ['status'], unique=False)
    op.create_index(op.f('ix_emailqueue_ticket_id'), 'emailqueue', ['ticket_id'], unique=False)
    op.create_table('scanevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('scanner_device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scanner_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scan_result', sa.Enum('granted', 'already_scanned', 'invalid', 'network_error', name='scanresult'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('network_latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanevent_scanner_device_id'), 'scanevent', ['scanner_device_id'], unique=False)
    op.create_index(op.f('ix_scanevent_ticket_id'), 'scanevent', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_scanevent_timestamp'), 'scanevent', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scanevent_timestamp'), table_name='scanevent')
    op.drop_index(op.f('ix_scanevent_ticket_id'), table_name='scanevent')
    op.drop_index(op.f('ix_scanevent_scanner_device_id'), table_name='scanevent')
    op.drop_table('scanevent')
    op.drop_index(op.f('ix_emailqueue_ticket_id'), table_name='emailqueue')
    op.drop_index(op.f('ix_emailqueue_status'), table_name='emailqueue')
    op.drop_index(op.f('ix_emailqueue_next_retry_at'), table_name='emailqueue')
    op.drop_table('emailqueue')
    op.drop_index(op.f('ix_ticket_is_scanned'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_host_email'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_guest_email'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_email_delivery_status'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_created_at'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
