/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutScannerRouteImport } from './routes/_layout/scanner'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutAdminDashboardRouteImport } from './routes/_layout/admin/dashboard'
import { Route as LayoutAdminTicketsIndexRouteImport } from './routes/_layout/admin/tickets/index'
import { Route as LayoutAdminTicketsUploadRouteImport } from './routes/_layout/admin/tickets/upload'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScannerRoute = LayoutScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminDashboardRoute = LayoutAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTicketsIndexRoute = LayoutAdminTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTicketsUploadRoute =
  LayoutAdminTicketsUploadRouteImport.update({
    id: '/tickets/upload',
    path: '/tickets/upload',
    getParentRoute: () => LayoutAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/scanner': typeof LayoutScannerRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/admin/tickets/upload': typeof LayoutAdminTicketsUploadRoute
  '/admin/tickets': typeof LayoutAdminTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/items': typeof LayoutItemsRoute
  '/scanner': typeof LayoutScannerRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/admin/tickets/upload': typeof LayoutAdminTicketsUploadRoute
  '/admin/tickets': typeof LayoutAdminTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/scanner': typeof LayoutScannerRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/dashboard': typeof LayoutAdminDashboardRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/admin/tickets/upload': typeof LayoutAdminTicketsUploadRoute
  '/_layout/admin/tickets/': typeof LayoutAdminTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/admin'
    | '/items'
    | '/scanner'
    | '/settings'
    | '/'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/tickets/upload'
    | '/admin/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/items'
    | '/scanner'
    | '/settings'
    | '/'
    | '/admin/dashboard'
    | '/admin'
    | '/admin/tickets/upload'
    | '/admin/tickets'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/scanner'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/dashboard'
    | '/_layout/admin/'
    | '/_layout/admin/tickets/upload'
    | '/_layout/admin/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scanner': {
      id: '/_layout/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof LayoutScannerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/dashboard': {
      id: '/_layout/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutAdminDashboardRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/tickets/': {
      id: '/_layout/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof LayoutAdminTicketsIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/tickets/upload': {
      id: '/_layout/admin/tickets/upload'
      path: '/tickets/upload'
      fullPath: '/admin/tickets/upload'
      preLoaderRoute: typeof LayoutAdminTicketsUploadRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminDashboardRoute: typeof LayoutAdminDashboardRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAdminTicketsUploadRoute: typeof LayoutAdminTicketsUploadRoute
  LayoutAdminTicketsIndexRoute: typeof LayoutAdminTicketsIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminDashboardRoute: LayoutAdminDashboardRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAdminTicketsUploadRoute: LayoutAdminTicketsUploadRoute,
  LayoutAdminTicketsIndexRoute: LayoutAdminTicketsIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutScannerRoute: typeof LayoutScannerRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutScannerRoute: LayoutScannerRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
